import os

DATABASE_URL = os.getenv("DATABASE_URL")

UPDATE_INTERVAL = 60

SYMBOLS = [
    "PETR4.SA","VALE3.SA","ITUB4.SA","BBDC4.SA",
    "BBAS3.SA","ABEV3.SA","SUZB3.SA","WEGE3.SA",
    "GGBR4.SA","LREN3.SA","ENGI11.SA","RENT3.SA",
    "AAPL34.SA","AMZO34.SA","MELI34.SA",
    "MSFT34.SA","NVDC34.SA","PFIZ34.SA"
]